spring:
  application:
    name: core
  datasource:
    # url: jdbc:mysql://mysql:3306/liyz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    url: jdbc:mysql://localhost:3306/liyz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: liyz
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
server:
  port: 8888

# application.yml
springdoc:
    api-docs:
        path: /api-docs  # OpenAPI JSON ??
    swagger-ui:
        path: /swagger-ui.html  # UI ????
        operations-sorter: method  # ?????
        tags-sorter: alpha        # ???????
        display-request-duration: true  # ??????
        try-it-out-enabled: true  # ??"Try it out"




mybatis:
  mapper-locations: classpath:mapper/*.xml  # XML 文件位置
  type-aliases-package: org.family.core.model
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印SQL



  redis:
    #host: redis
    host: localhost
    port: 6379
    password: liyazhou
    timeout: 3000ms  # 添加超时配置
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
